src/MovieResources-master/MovieResources/Areas/Manage/Controllers/AlbumController.cs
using MovieResources.Filters;
using MovieResources.Helpers;
using MovieResources.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MovieResources.Areas.Manage.Controllers
{
    public class AlbumController : Controller
    {
        MR_DataClassesDataContext _db = new MR_DataClassesDataContext();

        #region 专辑管理首页
        //
        // GET: /Manage/Album/
        [AdminFilter]
        public ActionResult Index(string search, int page = 1)
        {
            var query = from a in _db.tbl_Album
                        select a;

            if (!string.IsNullOrEmpty(search) && !string.IsNullOrWhiteSpace(search))
            {
                search = search.ToLower();
                query = (IOrderedQueryable<tbl_Album>)query.Where(s => s.album_Title.ToLower().Contains(search));
            }
            query = query.Skip((page - 1) * 20).Take(20).OrderByDescending(m => m.album_Time);
            List<ManageAlbumViewModel> albums = new List<ManageAlbumViewModel>();
            foreach (var item in query)
            {
                albums.Add(new ManageAlbumViewModel(item));
            }
            return View(albums);
        }
        #endregion

        #region 创建专辑
        //
        // GET: /Manage/Create/
        [AdminFilter]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Manage/Create/
        [HttpPost]
        [AdminFilter]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ManageAlbumViewModel model, System.Web.HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (file != null && file.ContentLength > 0)
            {
                var fileName = System.IO.Path.Combine(Request.MapPath("~/Content/Album/"), System.IO.Path.GetFileName(file.FileName));
                file.SaveAs(fileName);
                model.Cover = System.IO.Path.GetFileName(file.FileName);
            }
            else
            {
                model.Cover = "Album_1.jpg";
            }
            model.UserId = AccountManager.GetId(User.Identity.Name);
            AlbumManager.Create(model);
            return View(new ManageAlbumViewModel());
        }
        #endregion

        #region 修改专辑
        //
        // GET: /Manage/Edit/
        [AdminFilter]
        public ActionResult Edit(string id)
        {
            if (!AlbumManager.Exist(id))
            {
                return RedirectToAction("NotFound", "Error");
            }
            tbl_Album tblalbum = _db.tbl_Album.SingleOrDefault(s => s.album_Id == id);
            ManageAlbumViewModel album = new ManageAlbumViewModel(tblalbum);
            return View(album);
        }

        //
        // POST: /Manage/Edit/
        [HttpPost]
        [AdminFilter]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ManageAlbumViewModel model, System.Web.HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (file != null && file.ContentLength > 0)
            {
                var fileName = System.IO.Path.Combine(Request.MapPath("~/Content/Album/"), System.IO.Path.GetFileName(file.FileName));
                file.SaveAs(fileName);
                model.Cover = System.IO.Path.GetFileName(file.FileName);

                string oldCover = _db.tbl_Album.SingleOrDefault(a => a.album_Id == model.Id).album_Cover;
                if (model.Cover != oldCover && oldCover != "Album_1.jpg")
                {
                    ImageManager.Delete(Server.MapPath("~/Content/Album/" + oldCover));
                }
            }
            AlbumManager.Edit(model);
            ModelState.AddModelError("", "修改成功");
            return RedirectToAction("Edit", new { id = model.Id });
        }
        #endregion

        #region 删除专辑
        //
        // GET: /Manage/Delete/
        [AdminFilter]
        public ActionResult Delete(string id)
        {
            if (!AlbumManager.Exist(id))
            {
                return RedirectToAction("NotFound", "Error");
            }
            tbl_Album tblalbum = _db.tbl_Album.SingleOrDefault(s => s.album_Id == id);
            ManageAlbumViewModel album = new ManageAlbumViewModel(tblalbum);
            return View(album);
        }

        //
        // Post: /Manage/Delete/
        [HttpPost, ActionName("Delete")]
        [AdminFilter]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(string id)
        {
            if (!AlbumManager.Exist(id))
            {
                return RedirectToAction("NotFound", "Error");
            }

            string oldCover = _db.tbl_Album.SingleOrDefault(a => a.album_Id == id).album_Cover;
            if (oldCover != "Album_1.jpg")
            {
                ImageManager.Delete(Server.MapPath("~/Content/Album/" + oldCover));
            }
            AlbumManager.Delete(id);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

src/MovieResources-master/MovieResources/Controllers/AlbumController.cs
using MovieResources.Helpers;
using MovieResources.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MovieResources.Controllers
{
    public class AlbumController : Controller
    {
        private MR_DataClassesDataContext _db = new MR_DataClassesDataContext();

        #region 专辑首页
        //
        // GET: /Album/Index/
        public ActionResult Index()
        {
            var allalbum = _db.tbl_Album.OrderByDescending(a => a.album_Visit);
            List<AlbumListItem> model = new List<AlbumListItem>();
            foreach (var item in allalbum)
            {
                AlbumListItem album = new AlbumListItem(item);
                model.Add(album);
            }
            return View(model);
        }
        #endregion

        #region 新建专辑
        //
        // GET: /Album/Create/
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Album/Create/
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ManageAlbumViewModel model, System.Web.HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (file != null && file.ContentLength > 0)
            {
                var fileName = System.IO.Path.Combine(Request.MapPath("~/Content/Album/"), System.IO.Path.GetFileName(file.FileName));
                file.SaveAs(fileName);
                model.Cover = System.IO.Path.GetFileName(file.FileName);
            }
            else
            {
                model.Cover = "Album_1.jpg";
            }
            model.UserId = AccountManager.GetId(User.Identity.Name);
            model.Id = AlbumManager.Create(model);
            return RedirectToAction("Detail", new { id = model.Id });
        }
        #endregion

        #region 专辑详情页
        //
        // GET: /Album/Detail/
        public ActionResult Detail(string id, int page = 1)
        {
            if (!AlbumManager.Exist(id))
            {
                return RedirectToAction("NotFound", "Error");
            }

            tbl_Album tblalbum = _db.tbl_Album.SingleOrDefault(s => s.album_Id == id);
            AlbumViewModel album = new AlbumViewModel(tblalbum);
            if (tblalbum.album_User == AccountManager.GetId(User.Identity.Name))
            {
                album.IsCreator = true;
            }
            if (User.Identity.IsAuthenticated)
            {
                if (_db.tbl_Mark.SingleOrDefault(f => f.mark_Target == id && f.mark_User == AccountManager.GetId(User.Identity.Name) && f.mark_Type == 7) != null)
                {
                    album.HasFollow = true;
                }
            }

            List<AlbumItemViewModel> allItem = new List<AlbumItemViewModel>();
            //album.Items = new List<AlbumItemViewModel>();
            allItem = Newtonsoft.Json.JsonConvert.DeserializeObject<List<AlbumItemViewModel>>(album.ItemJson);
            album.Count = allItem.Count;
            album.Items = allItem.Skip((page - 1) * album.ItemSize).Take(album.ItemSize).ToList();
            foreach (var item in album.Items)
            {
                item.MovieInfo = new MovieViewModel(_db.tbl_Movie.SingleOrDefault(m => m.movie_Id == item.Movie));
            }

            album.Page = page;
            album.PagingCount = Convert.ToInt32(Math.Ceiling(Convert.ToDecimal(album.Count) / album.ItemSize));

            if (page > album.PagingCount && album.Items.Count > 0)
            {
                return RedirectToAction("NotFound", "Error");
            }

            AlbumManager.Visit(id);
            return View(album);
        }
        #endregion

        #region 修改专辑
        //
        // GET: /Album/Edit/
        [Authorize]
        public ActionResult Edit(string id)
        {
            if (!AlbumManager.Exist(id))
            {
                return RedirectToAction("NotFound", "Error");
            }
            ManageAlbumViewModel album = new ManageAlbumViewModel(_db.tbl_Album.SingleOrDefault(s => s.album_Id == id));
            return View(album);
        }

        //
        // POST: /Album/Edit/
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ManageAlbumViewModel model, System.Web.HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (file != null && file.ContentLength > 0)
            {
                var fileName = System.IO.Path.Combine(Request.MapPath("~/Content/Album/"), System.IO.Path.GetFileName(file.FileName));
                file.SaveAs(fileName);
                model.Cover = System.IO.Path.GetFileName(file.FileName);

                string oldCover = _db.tbl_Album.SingleOrDefault(a => a.album_Id == model.Id).album_Cover;
                if (model.Cover != oldCover && oldCover != "Album_1.jpg")
                {
                    ImageManager.Delete(Server.MapPath("~/Content/Album/" + oldCover));
                }
            }
            AlbumManager.Edit(model);
            ModelState.AddModelError("", "修改成功");
            return RedirectToAction("Edit", new { id = model.Id });
        }
        #endregion

        #region 删除专辑
        //
        // GET: /Album/Delete/
        [Authorize]
        public ActionResult Delete(string id, string returnurl)
        {
            if (!AlbumManager.Exist(id))
            {
                return RedirectToAction("NotFound", "Error");
            }
            ViewBag.ReturnUrl = returnurl;
            ManageAlbumViewModel album = new ManageAlbumViewModel(_db.tbl_Album.SingleOrDefault(s => s.album_Id == id));
            return View(album);
        }

        //
        // POST: /Album/Delete/
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(string id)
        {
            if (!AlbumManager.Exist(id))
            {
                return RedirectToAction("NotFound", "Error");
            }

            string oldCover = _db.tbl_Album.SingleOrDefault(a => a.album_Id == id).album_Cover;
            if (oldCover != "Album_1.jpg")
            {
                ImageManager.Delete(Server.MapPath("~/Content/Album/" + oldCover));
            }
            AlbumManager.Delete(id);
            return RedirectToAction("Index");
        }

        //
        // GET: /Album/Delete/
        public ActionResult CancelDelete(string returnurl)
        {
            return RedirectToLocal(returnurl);
        }
        #endregion

        #region 专辑项目增删
        //
        // POST: /Album/AddItem/
        [HttpPost]
        [Authorize]
        public ActionResult AddItem(string id, string movie, string note, string returnurl)
        {
            AlbumItemViewModel item = new AlbumItemViewModel();
            item.Movie = movie;
            item.Note = note;
            item.Time = DateTime.Now.ToString();
            AlbumManager.Add(id, item);
            return RedirectToLocal(returnurl);
        }

        //
        // GET: /Album/AddItem/
        [Authorize]
        public ActionResult DeleteItem(string id, string movie, string returnurl)
        {
            if (!AlbumManager.Exist(id))
            {
                return RedirectToAction("NotFound", "Error");
            }
            AlbumManager.Minus(id, movie);
            return RedirectToLocal(returnurl);
        }
        #endregion

        #region 帮助程序
        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (!Url.IsLocalUrl(returnUrl) && !string.IsNullOrEmpty(returnUrl) && !string.IsNullOrWhiteSpace(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }
        #endregion
    }
}

src/MovieResources-master/MovieResources/Views/Album/Create.cshtml
@model MovieResources.Models.ManageAlbumViewModel

@{
    ViewBag.Title = "创建新的专辑";
    ViewBag.PageType = 2;
}

@using (Html.BeginForm("Create", "Album", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "请填写 专辑名称" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Summary, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.EditorFor(model => model.Summary, new { htmlAttributes = new { @class = "form-control min-editor", placeholder = "请填写 专辑简介" } })
                    @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Cover, htmlAttributes: new { @class = "control-label" })
                <div>
                    <input type="file" name="file" class="form-control" placeholder="请选择图片" />
                    @Html.ValidationMessageFor(model => model.Cover, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="panel-footer">
            <input type="submit" value="确认新建" class="btn btn-primary btn-block" />
        </div>
    </div>
}

src/MovieResources-master/MovieResources/Views/Album/Delete.cshtml
@model MovieResources.Models.ManageAlbumViewModel

@{
    ViewBag.Title = "删除 " + Model.Title;
    ViewBag.PageType = 2;
}

<div class="panel panel-default">
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Summary)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Summary)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreateTime)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CreateTime)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AlterTime)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.AlterTime)
            </dd>
        </dl>
    </div>

    <div class="panel-footer">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="submit" value="确认删除" class="btn btn-primary" />
                <a class="btn btn-default" href="/Album/CancelDelete?returnurl=@ViewBag.ReturnUrl" title="取消">取消</a>
            </div>
        }
    </div>
</div>

src/MovieResources-master/MovieResources/Views/Album/Detail.cshtml
@model MovieResources.Models.AlbumViewModel

@{
    ViewBag.Title = Model.Title;
    ViewBag.PageType = 2;
}

<style>
    #div-back {
        height: 230px;
        padding: 10px;
        margin-bottom: 15px;
        background-color: #E6E6E6;
    }

    #div-card {
        padding: 8px;
        overflow: hidden;
        margin: 0px;
    }

    #div-image {
        width: 115px;
        height: 160px;
        float: left;
    }

    #div-info {
        height: 160px;
        margin-left: 125px;
    }
</style>

<div class="col-sm-8">
    <b style="font-size:28px;">@Model.Title</b>
    <div style="margin-top:5px;">
        <span>
            来自: <a href="/People/Index?id=@Model.UserId&returnurl=@Request.Url" class="link-text" target="_self" title="@Model.UserAccount 的主页">@Model.UserAccount</a>
        </span>&nbsp;&nbsp;&nbsp;&nbsp;
        <span>@Model.CreateTime 创建</span>&nbsp;&nbsp;&nbsp;&nbsp;
        <span>@Model.AlterTime 更新</span>
    </div>
    <p style="margin-top:10px;">@Model.Summary</p>
    <div style="margin-top:10px; margin-bottom:15px; ">

        @if (Model.IsCreator)
        {
            <a class="link-text" href="/Album/Edit?id=@Model.Id&returnurl=@Request.Url" title="修改">&gt;修改</a>
            <a class="link-text" href="/Album/Delete?id=@Model.Id&returnurl=@Request.Url" title="删除">&gt;删除</a>

            <a class="btn btn-xs btn-primary pull-right" title="添加内容" data-toggle="modal" data-target="#modalAdd"><span class="fa fa-plus"></span>添加内容</a>
        }
        else
        {
            if (Model.HasFollow)
            {
                <a class="btn btn-xs btn-primary" href="/Mark/Cancel?target=@Model.Id&type=7&returnurl=@Request.Url" title="取消关注"><span class="fa fa-star-o"></span>取消关注</a>
            }
            else
            {
                <a class="btn btn-xs btn-primary" href="/Mark/Create?target=@Model.Id&type=7&returnurl=@Request.Url" title="关注"><span class="fa fa-star-o"></span>关注</a>
            }
        }
    </div>

    <hr />

    @if (Model.Items.Count == 0)
    {
        <div class="text-center">这个专辑还没有内容(＃￣▽￣＃)</div>
    }

    @foreach (var item in Model.Items)
    {
        <div id="div-back">
            <div class="panel panel-default" id="div-card">
                <div id="div-image">
                    <a class="full-height" href="/Movie/Index?id=@item.MovieInfo.Id">
                        <img src="~/Content/Movie/@item.MovieInfo.Avatar" title="@item.MovieInfo.Title" class="img-responsive full-height full-width" />
                    </a>
                </div>
                <div id="div-info">
                    <div>
                        <a href="/Movie/Index?id=@item.MovieInfo.Id" target="_self">
                            <strong title="@item.MovieInfo.Title">@item.MovieInfo.Title</strong>
                        </a>
                        <a href="http://movie.douban.com/subject/@item.MovieInfo.DoubanID/" class="clr-doubangreen" title="跳转到豆瓣电影" target="_self">
                            @item.MovieInfo.Rating
                        </a>
                        <span class="label label-info font-small" style="padding:0px 3px;">@item.MovieInfo.Year</span>
                    </div>
                    <div class="text-overflow">
                        <strong>导演</strong>
                        @foreach (var celebitem in item.MovieInfo.Directors.Take(4))
                        {
                            if (!string.IsNullOrEmpty(celebitem.Id))
                            {
                                <a href="/Celeb/Index?id=@celebitem.Id" class="link-text" target="_self">@celebitem.Title</a>
                            }
                            else
                            {
                                <span>@celebitem.Title</span>
                            }
                        }
                    </div>
                    <div class="text-overflow">
                        <strong>类型</strong>
                        <span>@item.MovieInfo.Genres</span>
                    </div>
                    <div class="text-overflow">
                        <strong>编剧</strong>
                        @foreach (var celebitem in item.MovieInfo.Writers.Take(4))
                        {
                            if (!string.IsNullOrEmpty(celebitem.Id))
                            {
                                <a href="/Celeb/Index?id=@celebitem.Id" class="link-text" target="_self">@celebitem.Title</a>
                            }
                            else
                            {
                                <span>@celebitem.Title</span>
                            }
                        }
                    </div>
                    <div class="text-overflow">
                        <strong>主演</strong>
                        @foreach (var celebitem in item.MovieInfo.Casts.Take(4))
                        {
                            if (!string.IsNullOrEmpty(celebitem.Id))
                            {
                                <a href="/Celeb/Index?id=@celebitem.Id" class="link-text" target="_self">@celebitem.Title</a>
                            }
                            else
                            {
                                <span>@celebitem.Title</span>
                            }
                        }
                    </div>
                </div>
            </div>
            <div style="margin-top:10px;">
                <div style="display:inline-block;">
                    备注：<span>@item.Note</span>
                </div>
                @if (Model.IsCreator)
                {
                    <a href="/Album/DeleteItem?id=@Model.Id&movie=@item.MovieInfo.Id&returnurl=@Request.Url" class="link-text pull-right" title="删除 @item.MovieInfo.Title">删除</a>
                }
            </div>
        </div>
    }

    @if (Model.PagingCount > 1)
    {
        @MovieResources.Helpers.Controls.PageTagList(Model.Page, Model.PagingSize, Model.PagingCount, Request.Url.ToString())
    }

    <div class="modal fade" id="modalAdd" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                @using (Html.BeginForm("AddItem", "Album", new { id = Model.Id, returnurl = Request.Url }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            &times;
                        </button>
                        <h4 class="modal-title" id="myModalLabel">
                            添加内容
                        </h4>
                    </div>
                    <div class="modal-body" style="padding:15px 50px;">
                        <label class="control-label" for="movie" style="margin-top:0px;">电影编号</label>
                        <input name="movie" id="movie" class="form-control" placeholder="请输入电影编号" style="margin-top: 5px;" />
                        <label class="control-label" for="note" style="margin-top:12px;">备注</label>
                        <input name="note" id="note" class="form-control" style="margin-top:5px;" />
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            关闭
                        </button>
                        <input type="submit" class="btn btn-primary" value="提交">
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div class="col-sm-4" style="margin-top:15px; padding:0px 0px 0px 30px;">
    <b class="font-larger">什么是专辑&nbsp;&middot;&nbsp;&middot;&nbsp;&middot;&nbsp;&middot;&nbsp;&middot;&nbsp;&middot;</b>
    <p class="text-capitalize">专辑是收集好电影的工具。</p>
    <p class="text-capitalize">将你喜欢的电影收集到专辑中，方便以后找到。</p>
    <hr />

    <b class="font-larger">@Model.UserAccount 的其他专辑&nbsp;&middot;&nbsp;&middot;&nbsp;&middot;&nbsp;&middot;&nbsp;&middot;&nbsp;&middot;</b>
    <ul class="list-link" style="margin-top:10px;">
        @foreach (var item in Model.Albums)
        {
            <li>
                <a href="/Album/Detail?id=@item.Id" class="link-list-item">@item.Title</a>
            </li>
        }
    </ul>
</div>

src/MovieResources-master/MovieResources/Views/Album/Edit.cshtml
@model MovieResources.Models.ManageAlbumViewModel

@{
    ViewBag.Title = "修改专辑";
    ViewBag.PageType = 2;
}

@using (Html.BeginForm("Edit", "Album", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.UserId)
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "请填写 专辑名称" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Summary, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.EditorFor(model => model.Summary, new { htmlAttributes = new { @class = "form-control min-editor", placeholder = "请填写 专辑简介" } })
                    @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Cover, htmlAttributes: new { @class = "control-label" })
                <div>
                    <input type="file" name="file" class="form-control" placeholder="请选择图片" />
                    @Html.ValidationMessageFor(model => model.Cover, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="panel-footer">
            <input type="submit" value="确认修改" class="btn btn-primary" />
            <a class="btn btn-default" href="/Album/Detail?id=@Model.Id" title="取消">取消</a>
        </div>
    </div>
}

src/MovieResources-master/MovieResources/Views/Album/Index.cshtml
@model List<MovieResources.Models.AlbumListItem>

@{
    ViewBag.Title = "专辑";
    ViewBag.PageType = 2;
    ViewBag.NavType = 4;
}

<div class="panel panel-body text-center no-padding">
    <h4>专辑</h4>
</div>

<div class="panel panel-body" style="padding:10px;">
    @foreach (var item in Model)
    {
        <div class="col-sm-3" style="padding:10px;">
            <div class="album panel-float">

                <div class="album-avatar">
                    <a href="/Album/Detail?id=@item.Id" title="@item.Title" target="_self"><img src="~/Content/Album/@item.Cover" /></a>
                </div>

                <div class="album-info">
                    <a class="link-no-line text-overflow" href="/Album/Detail?id=@item.Id" target="_self" title="@item.Title">@item.Title</a>
                    <small>@item.Summary</small>
                </div>

                <div class="album-bottom">
                    <i class="fa fa-eye"></i><span> &nbsp;@item.VisitCount</span>
                    <i class="fa fa-heart"></i><span> &nbsp;@item.FollowCount</span>
                    @if (!string.IsNullOrEmpty(item.UserId))
                    {
                        <div class="album-user">
                            <a href="/People/Index?id=@item.UserId" data-toggle="tooltip" data-placement="top" title="@item.UserAccount" target="_self">
                                <i class="fa fa-user"></i>
                            </a>
                        </div>
                    }
                </div>
            </div>
        </div>
    }
</div>