src/MovieResources-master/MovieResources/Controllers/AskController.cs
using MovieResources.Helpers;
using MovieResources.Models;
using System.Linq;
using System.Web.Mvc;

namespace MovieResources.Controllers
{
    public class AskController : Controller
    {
        private MR_DataClassesDataContext _db = new MR_DataClassesDataContext();

        #region 求资源首页
        //
        // GET: /Ask/Index/
        public ActionResult Index()
        {
            IndexAskViewModel model = new IndexAskViewModel();

            var queryall = _db.tbl_Ask.OrderByDescending(a => a.ask_Time);

            foreach (var item in queryall)
            {
                AskViewModel ask = new AskViewModel(item);
                if (User.Identity.IsAuthenticated)
                {
                    string user = AccountManager.GetId(User.Identity.Name);
                    if ((item.ask_User == user) || (_db.tbl_Mark.SingleOrDefault(w => w.mark_User == user && w.mark_Target == item.ask_Id && w.mark_Type == 6) != null))
                    {
                        ask.hadWith = true;
                    }
                }
                model.All.Add(ask);
            }

            var querymost = _db.tbl_Ask.OrderByDescending(a => a.ask_With).Take(20);
            foreach (var item in querymost)
            {
                AskViewModel ask = new AskViewModel(item);
                model.Most.Add(ask);
            }

            var queryover = _db.tbl_Ask.Where(a => a.ask_State == true).Take(20);
            foreach (var item in queryover)
            {
                AskViewModel ask = new AskViewModel(item);
                model.Over.Add(ask);
            }

            return View(model);
        }
        #endregion

        #region 创建求资源
        //
        // GET: /Ask/Create/
        [Authorize]
        public ActionResult Create(string id)
        {
            if (!MovieManager.Exist(id))
            {
                return RedirectToAction("NotFound", "Error");
            }
            ManageAskViewModel ask = new ManageAskViewModel() { MovieId = id, MovieTitle = _db.tbl_Movie.Single(m => m.movie_Id == id).movie_Title };
            return View(ask);
        }

        //
        // POST: /Ask/Create/
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ManageAskViewModel model)
        {
            if (!string.IsNullOrEmpty(model.Note) && !string.IsNullOrWhiteSpace(model.Note))
            {
                var user = _db.tbl_UserAccount.SingleOrDefault(u => u.user_Account == User.Identity.Name);
                model.User = user.user_Id;
                AskManager.Create(model);
                return RedirectToAction("Index", "Movie", new { id = model.MovieId });
            }
            else
            {
                ModelState.AddModelError("", "备注 不能为空，请重新输入 备注。");
                return View(model);
            }
        }
        #endregion

        #region 删除求资源
        //
        // GET: /Ask/Delete/
        [Authorize]
        public ActionResult Delete(string id, string returnurl)
        {
            if (!AskManager.Exist(id))
            {
                return RedirectToAction("NotFound", "Error");
            }

            var user = _db.tbl_UserAccount.SingleOrDefault(m => m.user_Account == User.Identity.Name).user_Id;
            var favor = _db.tbl_Ask.SingleOrDefault(m => m.ask_Id == id && m.ask_User == user);
            if (favor != null)
            {
                AskManager.Delete(id);
            }
            return Redirect(returnurl);
        }
        #endregion

        #region 已求到
        //
        // GET: /Ask/Over/
        [Authorize]
        public ActionResult Over(string id, string returnUrl)
        {
            if (!AskManager.Exist(id))
            {
                return RedirectToAction("NotFound", "Error");
            }
            string user = AccountManager.GetId(User.Identity.Name);

            if (_db.tbl_Mark.SingleOrDefault(w => w.mark_Target == id && w.mark_User == user && w.mark_Type == 6) == null)
            {
                AskManager.Over(id);
            }
            return RedirectToLocal(returnUrl);
        }
        #endregion

        #region 帮助程序
        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (!Url.IsLocalUrl(returnUrl) && !string.IsNullOrEmpty(returnUrl) && !string.IsNullOrWhiteSpace(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }
        #endregion
    }
}

src/MovieResources-master/MovieResources/Controllers/MineController.cs
using MovieResources.Helpers;
using MovieResources.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieResources.Controllers
{
    public class MineController : Controller
    {
        MR_DataClassesDataContext _db = new MR_DataClassesDataContext();

        #region 用户主页
        //
        // GET: /Mine/Index/
        [Authorize]
        public ActionResult Index()
        {
            MineViewModel model = new MineViewModel();
            model.Account = User.Identity.Name;
            model.Avatar = _db.tbl_UserAccount.Single(m => m.user_Account == model.Account).user_Avatar;
            model.Cover = _db.tbl_UserAccount.Single(m => m.user_Account == model.Account).user_Cover;
            model.Id = AccountManager.GetId(model.Account);

            var plans = _db.tbl_Mark.Where(m => m.mark_User == model.Id && m.mark_Type == 1).OrderByDescending(m => m.mark_Time);
            model.PlanCount = plans.Count();
            model.MoviePlans = new List<MarkItem>();
            if (model.PlanCount != 0)
            {
                foreach (var item in plans.Take(10))
                {
                    MarkItem mitem = new MarkItem();
                    mitem.Id = item.mark_Target;
                    mitem.Avatar = _db.tbl_Movie.Single(m => m.movie_Id == item.mark_Target).movie_Avatar;
                    mitem.Title = _db.tbl_Movie.Single(m => m.movie_Id == item.mark_Target).movie_Title;
                    model.MoviePlans.Add(mitem);
                }
            }

            var finishs = _db.tbl_Mark.Where(m => m.mark_User == model.Id && m.mark_Type == 2).OrderByDescending(m => m.mark_Time);
            model.FinishCount = finishs.Count();
            model.MovieFinishs = new List<MarkItem>();
            if (model.FinishCount != 0)
            {
                foreach (var item in finishs.Take(10))
                {
                    MarkItem mitem = new MarkItem();
                    mitem.Id = item.mark_Target;
                    mitem.Avatar = _db.tbl_Movie.Single(m => m.movie_Id == item.mark_Target).movie_Avatar;
                    mitem.Title = _db.tbl_Movie.Single(m => m.movie_Id == item.mark_Target).movie_Title;
                    model.MovieFinishs.Add(mitem);
                }
            }

            var favors = _db.tbl_Mark.Where(m => m.mark_User == model.Id && m.mark_Type == 3).OrderByDescending(m => m.mark_Time);
            model.FavorCount = favors.Count();
            model.MovieFavors = new List<MarkItem>();
            if (model.FavorCount != 0)
            {
                foreach (var item in favors.Take(10))
                {
                    MarkItem mitem = new MarkItem();
                    mitem.Id = item.mark_Target;
                    mitem.Avatar = _db.tbl_Movie.Single(m => m.movie_Id == item.mark_Target).movie_Avatar;
                    mitem.Title = _db.tbl_Movie.Single(m => m.movie_Id == item.mark_Target).movie_Title;
                    model.MovieFavors.Add(mitem);
                }
            }

            var collects = _db.tbl_Mark.Where(m => m.mark_User == model.Id && m.mark_Type == 4).OrderByDescending(m => m.mark_Time);
            model.CollectCount = collects.Count();
            model.CelebCollects = new List<MarkItem>();
            if (model.CollectCount != 0)
            {
                foreach (var item in collects.Take(10))
                {
                    MarkItem mitem = new MarkItem();
                    mitem.Id = item.mark_Target;
                    mitem.Avatar = _db.tbl_Celebrity.Single(m => m.celeb_Id == item.mark_Target).celeb_Avatar;
                    mitem.Title = _db.tbl_Celebrity.Single(m => m.celeb_Id == item.mark_Target).celeb_Name;
                    model.CelebCollects.Add(mitem);
                }
            }

            var albums = _db.tbl_Album.Where(a => a.album_User == model.Id).OrderByDescending(a => a.album_AlterTime);
            model.AlbumCount = albums.Count();
            model.Albums = new List<AlbumListItem>();
            if (model.AlbumCount != 0)
            {
                foreach (var item in albums)
                {
                    model.Albums.Add(new AlbumListItem(item));
                }
            }

            var comments = _db.tbl_Comment.Where(c => c.cmt_User == model.Id).OrderByDescending(c => c.cmt_Time);
            model.CommentCount = comments.Count();
            model.Comments = new List<CommentItem>();
            if (model.AlbumCount != 0)
            {
                foreach (var item in comments)
                {
                    CommentItem citem = new CommentItem();
                    citem.MovieID = item.cmt_Movie;
                    citem.MovieTitle = MovieManager.GetTitle(item.cmt_Movie);
                    citem.Comment = item.cmt_Content;
                    citem.Time = ((System.DateTime)item.cmt_Time).ToString("yyyy-MM-dd hh:mm:ss");
                    model.Comments.Add(citem);
                }
            }

            return View(model);
        }
        #endregion

        #region 用户基本信息修改
        //
        // GET: /Mine/ChangeAvatar/
        [Authorize]
        public ActionResult ChangeAvatar()
        {
            ChangeAvatarViewModel model = new ChangeAvatarViewModel();
            model.Account = User.Identity.Name;
            model.Avatar = _db.tbl_UserAccount.Single(m => m.user_Account == model.Account).user_Avatar;

            return View(model);
        }

        //
        // POST: /Mine/ChangeAvatar/
        [Authorize]
        [HttpPost]
        public ActionResult ChangeAvatar(ChangeAvatarViewModel model, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.Id = _db.tbl_UserAccount.Single(m => m.user_Account == User.Identity.Name).user_Id;

            if (file != null && file.ContentLength > 0)
            {
                var fileName = System.IO.Path.Combine(Request.MapPath("~/Content/User/Avatar/"), model.Id + System.IO.Path.GetFileName(file.FileName));
                file.SaveAs(fileName);
                model.Avatar = model.Id + System.IO.Path.GetFileName(file.FileName);
                string oldAvatar = _db.tbl_UserAccount.Single(m => m.user_Account == User.Identity.Name).user_Avatar;
                if (model.Avatar != oldAvatar && oldAvatar != "User_1.jpg")
                {
                    ImageManager.Delete(Server.MapPath("~/Content/User/Avatar/" + oldAvatar));
                }
            }
            else
            {
                ModelState.AddModelError("", "请选择一张图片");
                model.Avatar = _db.tbl_UserAccount.Single(m => m.user_Account == User.Identity.Name).user_Avatar;
                return View(model);
            }
            var result = AccountManager.ChangeAvatar(model);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", result.Error);
            }
            return View(model);
        }

        //
        // GET: /Mine/ChangePassword/
        [Authorize]
        public ActionResult ChangePassword()
        {
            ChangePasswordViewModel model = new ChangePasswordViewModel();
            model.Account = User.Identity.Name;
            model.Avatar = _db.tbl_UserAccount.Single(m => m.user_Account == model.Account).user_Avatar;
            return View(model);
        }

        //
        // POST: /Mine/ChangePassword/
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = AccountManager.ChangePassword(User.Identity.Name, model.OldPassword, model.NewPassword);
            if (result.Succeeded)
            {
                AccountManager.SignIn(User.Identity.Name);
            }
            ModelState.AddModelError("", result.Error);
            return View(model);
        }

        //
        // GET: /Mine/ChangeCover/
        [Authorize]
        public ActionResult ChangeCover()
        {
            ChangeCoverViewModel model = new ChangeCoverViewModel();
            model.Account = User.Identity.Name;
            model.Cover = _db.tbl_UserAccount.Single(m => m.user_Account == model.Account).user_Cover;
            model.Avatar = _db.tbl_UserAccount.Single(m => m.user_Account == model.Account).user_Avatar;

            return View(model);
        }

        //
        // POST: /Mine/ChangeCover/
        [Authorize]
        [HttpPost]
        public ActionResult ChangeCover(ChangeCoverViewModel model, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.Id = _db.tbl_UserAccount.Single(m => m.user_Account == User.Identity.Name).user_Id;

            if (file != null && file.ContentLength > 0)
            {
                var fileName = System.IO.Path.Combine(Request.MapPath("~/Content/User/Cover/"), model.Id + System.IO.Path.GetFileName(file.FileName));
                file.SaveAs(fileName);
                model.Cover = model.Id + System.IO.Path.GetFileName(file.FileName);
                string oldCover = _db.tbl_UserAccount.Single(m => m.user_Account == User.Identity.Name).user_Cover;
                if (model.Cover != oldCover && oldCover != "Cover_1.jpg" && oldCover != "Cover_2.jpg")
                {
                    ImageManager.Delete(Server.MapPath("~/Content/User/Cover/" + oldCover));
                }
            }
            else
            {
                ModelState.AddModelError("", "请选择一张图片");
                model.Cover = _db.tbl_UserAccount.Single(m => m.user_Account == User.Identity.Name).user_Avatar;
                return View(model);
            }

src/MovieResources-master/MovieResources/Views/Shared/_LayoutPage.cshtml
@{
    Layout = "~/Views/Shared/_LayoutWide.cshtml";
}

<div class="container">
    @RenderBody()
</div>

src/MovieResources-master/MovieResources/Views/Shared/_LayoutWide.cshtml
@using System.Configuration;

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @ConfigurationManager.AppSettings.Get("WebsiteName")</title>
    @Styles.Render("~/Styles/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {
            $(".tipup").tooltip();
        });
    </script>
    <style>
        .link-sub {
            padding: 0px;
            color: #FAFAFA;
            margin-left: 8px;
            margin-right: 8px;
        }

            .link-sub:hover,
            .link-sub:focus,
            .link-sub:active {
                color: #E6E6E6;
                text-decoration: none;
            }

        .span-search {
            border-width: 0px;
            background-color: #FFFFFF;
            border-radius: 0px;
        }

        .input-search {
            border-width: 0px;
            border-radius: 0px;
        }

            .input-search:focus,
            .input-search:active {
                -webkit-box-shadow: 0 0 16px #10761A;
                -moz-box-shadow: 0 0 16px #10761A;
                box-shadow: 0 0 16px #10761A;
            }

        .btn-search {
            border-width: 0px;
            border-radius: 0px;
        }

            .btn-search:hover {
                color: #10761A;
            }
    </style>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(@ConfigurationManager.AppSettings.Get("WebsiteName"), "Index", "Home", new { Area = "" }, new { @class = "navbar-brand", title = @ConfigurationManager.AppSettings.Get("WebsiteName") + " " + @ConfigurationManager.AppSettings.Get("WebsiteSubTitle"), style = "font-family:'Weston Free'; " })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (ViewBag.NavType == 1)
                    {
                        <li class="active">@Html.ActionLink("首页", "Index", "Home")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("首页", "Index", "Home")</li>
                    }
                    @if (ViewBag.NavType == 2)
                    {
                        <li class="active">@Html.ActionLink("选电影", "Index", "Search")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("选电影", "Index", "Search")</li>
                    }
                    @if (ViewBag.NavType == 3)
                    {
                        <li class="active">@Html.ActionLink("求资源", "Index", "Ask")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("求资源", "Index", "Ask")</li>
                    }
                    @if (ViewBag.NavType == 4)
                    {
                        <li class="active">@Html.ActionLink("专辑", "Index", "Album")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("专辑", "Index", "Album")</li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (ViewBag.NavType == 5)
                        {
                            <li class="active">@Html.ActionLink("我的主页", "Index", "Mine")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("我的主页", "Index", "Mine")</li>
                        }
                    }
                    <li role="separator" class="divider"></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    @if (ViewBag.PageType == 1)//首页
    {
        <div style="background-color:#3B9047; padding:5px; margin-bottom:20px;" class="hidden-xs">
            <div class="container">
                <div class="row no-margin no-padding">
                    <a class="link-sub">热门分类：</a>
                    <a class="link-sub" href="/Search/Index?country=10" target="_self">大陆</a>
                    <a class="link-sub" href="/Search/Index?country=11" target="_self">香港</a>
                    <a class="link-sub" href="/Search/Index?country=12" target="_self">美国</a>
                    <a class="link-sub" href="/Search/Index?country=14" target="_self">日本</a>
                    <a class="link-sub" href="/Search/Index?genre=14" target="_self">动作</a>
                    <a class="link-sub" href="/Search/Index?genre=12" target="_self">喜剧</a>
                    <a class="link-sub" href="/Search/Index?genre=15" target="_self">科幻</a>
                    <a class="link-sub" href="/Search/Index?genre=22" target="_self">悬疑</a>
                    <a class="link-sub" href="/Search/Index?genre=13" target="_self">爱情</a>
                </div>
            </div>
        </div>
    }
    else if (ViewBag.PageType == 2)//一般页面
    {
        <div style="background-color:#3B9047; padding:10px 0px; margin-bottom:20px;">
            @using (Html.BeginForm("Index", "Search", FormMethod.Post, new { @class = "form-horizontal container", role = "form", id = "searchForm" }))
            {
                <div class="input-group col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
                    <input type="search" class="form-control input-search" placeholder="搜索 电影" name="search" />
                    <span class="input-group-btn span-search">
                        <a title="搜索" class="btn btn-default btn-search" href="javascript:document.getElementById('searchForm').submit()">
                            <i class="fa fa-search"></i>
                        </a>
                    </span>
                </div>
            }
        </div>
    }

    @RenderBody()

    <footer class="site-footer bg-doubangreen" role="contentinfo">
        <div style="height:27px; background-color:#DCDCDC;"></div>
        <div class="site-info" style="padding:40px 0px 30px 0px; margin:0px;">
            <p style="text-align:center; color:#F2F2F2;">&copy; @DateTime.Now.Year &nbsp;&nbsp;&nbsp;&nbsp;<a href="/Home/Index" style="font-family:'Weston Free'; color:inherit; text-decoration:underline;" title="@ConfigurationManager.AppSettings.Get("WebsiteName") @ConfigurationManager.AppSettings.Get("WebsiteSubTitle")">@ConfigurationManager.AppSettings.Get("WebsiteName")</a> - @ConfigurationManager.AppSettings.Get("WebsiteSubTitle")</p>
        </div>
    </footer>

    @RenderSection("scripts", required: false)
</body>
</html>